### ISSUE TITLE
Simple-schema clean() parameters

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#12]
templates:form call the simple-schema `clean()` method [here](https://github.com/meteortemplates/forms/blob/master/templates:forms.coffee#L285).

The issue is that, as explain in [simple-schema doc](https://github.com/aldeed/meteor-simple-
schema#cleaning-data), `clean()` takes arguments that one might want to change. For example, `removeEmptyStrings` default value is painful and you often want to change it. See [this discussion](https://github.com/aldeed/meteor-collection2/issues/78).

I see 2 ways to solve this:
1- Allow setting `clean()` parameters somewhere
2- Find a way to allow user to call `clean()` by himself if he wants to

**Comment by steph643** [comment]
Might be related or not:
At some point, if you decide to develop your own schema package, I will be happy to discuss about it and try it.

**Comment by jonjamz** [comment]
Hey--thanks for the offer on the schema package. I've thought about it, because Simple Schema is actually quite complex.

You can specify your own function to bypass the `getValidationValue` function when you create an element, using the `validationValue` method (shown in the example here):

https://github.com/meteortemplates/forms#reactiveformscreateelement

This allows you to call `clean()` by yourself. I think what I need to do here is simply allow you to pass the second argument in for the options.

**Comment by steph643** [comment]
Yes, I think your proposal would solve the issue.

**Comment by steph643** [comment]
However this is not the ideal solution.
`ReactiveForms.createElement()` is supposed to be used to declare generic and reusable elements, for example a `bootstrapInput`. So I don't think this is the right place to specify `clean()` arguments. Those arguments are tied more to a specific schema.
What you suggest is a nice and simple workaround, which I think is sufficient for now.
But in the end, my opinion is that you will need to replace simple-schema, whose purpose is really to serve as a foundation for collection2 and autoform.

**Comment by jonjamz** [comment]
Sure, the callback I mentioned is more for taking custom values out of HTML and converting them into data that would match an appropriate schema. For example, a multi-select form into an array of values or a toggle button into a boolean. 

Perhaps the clean function should be removed from here altogether, and rather passed into the action function.

With a custom schema package I would try to keep the same format for input as Simple Schema, so that people who already use that package wouldn't have to rewrite their schemas to use this package.

**Comment by steph643** [comment]
I haven't studied in details what a minimalist schema package should look like, but I am not sure a clean() function should be part of it.
If you start a feature list, I will try to add some items.
Format compatibility with simple-schema is definitely a must. So is probably a conversion feature to generate from and to simple-schema objects.

**Comment by steph643** [comment]
Fix works great.
