### ISSUE TITLE
Extension to simple-schema does not seem to work

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#5]
Whenever I add an 'instructions' field to my schema, I got the following error:
```

Error: Invalid definition for title field.
W20150115-12:15:57.350(1)? (STDERR)     at packages/aldeed:simple-schema/simple-schema.js:62:1
W20150115-12:15:57.351(1)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150115-12:15:57.351(1)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed:simple-schema/simple-schema.js:59:1)
W20150115-12:15:57.351(1)? (STDERR)     at app/collections/projects.js:1:253
W20150115-12:15:57.351(1)? (STDERR)     at app/collections/projects.js:3:3
```
My schema:
```
Projects.schema = new SimpleSchema(
	{
	title:
		{
		type: String,
		regEx: /^[a-z0-9A-Z]{1,50}$/,
		min: 1,
		max: 50,
		instructions: 'whatever'
		},
        ...
    }
```

**Comment by jonjamz** [comment]
This error seems odd, as I've coded the extension using the normal SimpleSchema syntax. I'm also using `instructions` in the live demo and in all my other testing it's worked fine.

I'll try to do more extensive testing at some point today.

**Comment by jonjamz** [comment]
I just copied your exact title schema into my example project and it worked.

I believe the problem is here:

https://github.com/meteortemplates/forms/blob/master/package.js#L23

Your schema seems to be in `app/collections` which loads on both the client and server. But my `simple-schema.coffee` file is only loaded on the client.

I'll fix this right now.

**Comment by jonjamz** [comment]
Tested and working in both environments. Just run `meteor update templates:forms`. Thanks.

**Comment by steph643** [comment]
Works great, thanks!
