### ISSUE TITLE
Simplify Package One Level Further

### ISSUE THREAD

**Issue by msavin** [meteortemplates/forms#58]
The abstractions are great, but I believe they could/should be simplified one level further:

```html
<template name="form">
	<form name="formData">
		<input name="name" type="text">
		<input name="email" type="text"><br>
		<input type="submit"><br>
	</form><br>
</template>
```

```javascript
Template.form.events({
	'submit': function () {
		console.log(template.formData) // Object
	}
});
```

**Comment by steph643** [comment]
That would be great.
In your idea, how do you pass the schema and initial field values? How do you define helpers to get validation status from within the template?

**Comment by msavin** [comment]
It's very high level - I haven't really thought about the implementation. I'd guess one way to start would be to parse the template HTML.

**Comment by steph643** [comment]
That sounds like a long way to go...
I think simplyfing the doc would be a good start. See my proposal for a new doc here: 
https://github.com/steph643/meteor-issue-3194/blob/master/old/README2.md

**Comment by jonjamz** [comment]
I actually *could* create an abstraction for templates that pulls up an internal form data context, similar to how Blaze has `Template.instance()`. 

But you could build your use case really simply with pure Blaze, as you seem to not need any of the features of this package other than to take data from elements by name and store them by that same name in an object, which you can then access from the `submit` event.

I have a few other thoughts surrounding this idea as it pertains to this package:

* It involves automatically capturing events for various HTML form elements, which is a bit assumptive and out of the scope of this package. That said, I could see somebody building a Form Block with this functionality baked in and sharing it once we set up a place to share these components. The package doesn't stop you from adding your own event handlers, helpers, etc. to a Form Block or Element.
* It's important to note that reusable Elements in this package, unlike stock HTML elements, search for a surrounding Form Block's data context when they are created. There are a lot of good things that come from this, for example we capture Element events at the Element-level and not at the Form Block level, allowing for Element-level transforms and such. I'd suggest having a look through the codebase at how Elements get set up. 
* You might think that creating reusable form components (like a template with just an `input` element inside it) and registering them is too much work to start with, but I think it's a case where a small amount of extra initial work saves you a ton of other work as your form needs grow. 

I'm going to close this issue for now, but I'll keep the idea in the back of my mind as I continue to develop this package. As @steph643 said, the underlying reason you might want to simplify the package to this level might be because it's not easy enough for new people to get started via the docs. We also really need to get a community going where people can share components.
