### ISSUE TITLE
Can you access a field 'value' outside of it's element block

### ISSUE THREAD

**Issue by eoliphan** [meteortemplates/forms#76]
Hi, I am trying to do some conditional display of fields, etc.   In reading the docs I see that I can grab an elements 'value' but inside it's definition.  In order to do my conditional display, I need to be able to do something like {{#if element.value}} ... inside the form block. Is this possible?

**Comment by jonjamz** [comment]
You should be able to access passed-in data (perhaps with `{{data.fieldName}}`, but accessing the values of inner elements as user input happens is probably not currently possible, although a future update could expose that because the data from elements is all stored in the form block instance anyway.

Would you be interested in contributing to this feature?

**Comment by eoliphan** [comment]
Once I get done with what I'm working on I can take a look

**Comment by jonjamz** [comment]
This functionality has been added as of `v2.1.0`. Please see the `History.md` file for specifics. I will add an example into the docs soon. It's a pretty cool feature!
