### ISSUE TITLE
'data' parameter required to be a plain object

### ISSUE THREAD

**Issue by steph643** [meteortemplates/forms#9]
[This check](https://github.com/meteortemplates/forms/blob/master/templates:forms.coffee#L26) is annoying, because it obliges you to pass a plain Object as 'data'.

It is ok if you got this objects directly from a Mongo collection. However, if you use an object-oriented scheme, what you got is an Object with prototypes, which will not pass the check.

It is the case, for example, if you use [meteor-collection-helpers](https://github.com/dburles/meteor-collection-helpers).

Workaround (painful):
```
{{#basicForm schema=schema data=th_dataAsPlainObject action=action}}
    ...
{{/basicForm}}

Template.xxxxx.helpers({
    th_dataAsPlainObject: function() {
        return _.clone(this.data);
    }
});

```

**Comment by jonjamz** [comment]
Ah--I had no intention of enforcing that restriction on objects.

I wouldn't want to make it `Match.Any` because I'm expecting the data to be in object-form:

https://github.com/meteortemplates/forms/blob/master/templates:forms.coffee#L243

Perhaps this would work better?

```coffeescript
Match.Where (x) ->
  return _.isObject(x)
```

The Underscore method seems to not be restricted to plain objects. http://underscorejs.org/#isObject

Will test later.

**Comment by jonjamz** [comment]
Will publish this with the next update.

**Comment by steph643** [comment]
Sounds great!

**Comment by jonjamz** [comment]
Update 1.7 has been published, check the changelog to see the latest.

**Comment by steph643** [comment]
Works like a charm, thanks!
